### ISSUE TITLE
help

### ISSUE THREAD

**Issue by yekayee** [adrian13508/Tiktok_Live_Game#1]
can u create full tutorial?

**Comment by adrian13508** [comment]
Hi, I will do full guide how to run it. Newer supposed that someone would like it. Give me 2 days to prepare good instructions and change build to make it simpler.

**Comment by romanu77** [comment]
Hi! I'm interested too. Any updates on instructions and build changing?

**Comment by yekayee** [comment]
can u create live vs game? like fighting game, if they give player reduce hp

**Comment by romanu77** [comment]
> can u create live vs game? like fighting game, if they give player reduce hp

hi! have you managed to run the game?

**Comment by yekayee** [comment]
i can run, but cant live with tiktok

**Comment by romanu77** [comment]
> i can run, but cant live with tiktok

Can you please help me run it?
I don't know how to  do this step -> "To run game: 1.Run virtual environment by running bin/activate "

**Comment by yekayee** [comment]
> It's tricky to run it directly from PC. You should have unlocked service streaming via RMTP link by TikTok or you can stream from phone placed in front of screen od PC. There is also an option to stream via LoolaTV but its paid approx. 25USD/month and had lag about 15 seconds.
> 
> Sorry to all of you for nor answering but had too much on my head lately. I'll try to fix instructions and add more functions to this game. If you have any tips od thoughts about this script please contact me or write here I will try to apply them to code to upgrade it.
> 
> Cheers!!

i can stream via rmtp

**Comment by yekayee** [comment]
u can create game like this with pygame https://www.youtube.com/watch?v=s5bd9KMSSW4&ab_channel=CodingWithRuss
and control them with gift from ppl in tiktok, if they gft p1 or p2 will reduce hp

**Comment by r0m41** [comment]
Help
![game](https://user-images.githubusercontent.com/64919602/223709157-8bd719e9-717b-4d6b-84d7-917d9793f11e.jpg)
